-- Remover tabelas com dependências
DROP TABLE exercicios CASCADE CONSTRAINTS;
DROP TABLE academias CASCADE CONSTRAINTS;
DROP TABLE praticantes CASCADE CONSTRAINTS;
DROP TABLE tb_endereco CASCADE CONSTRAINTS;
DROP TABLE tb_users CASCADE CONSTRAINTS;

CREATE TABLE academias (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cnpj VARCHAR2(255),
    nome VARCHAR2(255),
    endereco_id NUMBER,
    user_id NUMBER
);

CREATE TABLE exercicios (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    km FLOAT NOT NULL,
    pontos FLOAT NOT NULL,
    tipo NUMBER,
    academia_id NUMBER,
    praticante_id NUMBER
);

CREATE TABLE praticantes (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cpf VARCHAR2(255),
    data_nascimento DATE,
    email VARCHAR2(255),
    pontos FLOAT NOT NULL,
    sexo NUMBER
);

CREATE TABLE tb_endereco (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bairro VARCHAR2(255),
    cep VARCHAR2(255),
    cidade VARCHAR2(255),
    estado VARCHAR2(255),
    numero VARCHAR2(255),
    rua VARCHAR2(255)
);

CREATE TABLE tb_users (
    id NUMBER PRIMARY KEY,
    email VARCHAR2(255),
    password VARCHAR2(255),
    username VARCHAR2(255)
);

-- Adicionar constraints únicas
ALTER TABLE academias 
    ADD CONSTRAINT UK_academias_endereco UNIQUE (endereco_id);

ALTER TABLE academias 
    ADD CONSTRAINT UK_academias_user UNIQUE (user_id);
    
    
-- Adicionar constraints de chave estrangeira
ALTER TABLE academias 
    ADD CONSTRAINT FK_academias_endereco FOREIGN KEY (endereco_id) REFERENCES tb_endereco(id);

ALTER TABLE academias 
    ADD CONSTRAINT FK_academias_user FOREIGN KEY (user_id) REFERENCES tb_users(id);

ALTER TABLE exercicios 
    ADD CONSTRAINT FK_exercicios_academia FOREIGN KEY (academia_id) REFERENCES academias(id);

ALTER TABLE exercicios 
    ADD CONSTRAINT FK_exercicios_praticante FOREIGN KEY (praticante_id) REFERENCES praticantes(id);
    
COMMIT;


-- Inserção de dados na tabela 'praticantes'
INSERT INTO praticantes (cpf, data_nascimento, email, pontos, sexo) 
VALUES ('58840938028', TO_DATE('1990-05-20', 'YYYY-MM-DD'), 'praticante1@example.com', 0, 1);

INSERT INTO praticantes (cpf, data_nascimento, email, pontos, sexo) 
VALUES ('86966735060', TO_DATE('1985-08-15', 'YYYY-MM-DD'), 'praticante2@example.com',0, 2);

INSERT INTO praticantes (cpf, data_nascimento, email, pontos, sexo) 
VALUES ('91861703090', TO_DATE('2000-12-10', 'YYYY-MM-DD'), 'praticante3@example.com', 0, 1);

-- Commit para confirmar as alterações
COMMIT;

-- Selecionar todos os registros da tabela academias
SELECT * FROM academias;
-- Selecionar todos os registros da tabela exercicios
SELECT * FROM exercicios;
-- Selecionar todos os registros da tabela praticantes
SELECT * FROM praticantes;
-- Selecionar todos os registros da tabela tb_endereco
SELECT * FROM tb_endereco;
-- Selecionar todos os registros da tabela tb_users
SELECT * FROM tb_users;
